### ISSUE TITLE
Broken link to sequel documentation

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#412]
http://www.equalizergraphics.com/api.html
 
Contains a link to
 
http://www.equalizergraphics.com/documents/Developer/API/sequel/namespaceseq.html
 
which results in a 404 Not found
 
What Is the correct link?
Can you please fix it in the webpage?
 
Thanks
Ruben Garcia
(I submitted this bug report on  10/22/2014 10:00 AM to info@equalizergraphics.com with no response; if this address is no longer valid it should be removed from the web site).

**Comment by eile** [comment]
Working on it.

**Comment by eile** [comment]
Docs on eyescale.github.io now contain Sequel doc.

**Comment by RubenGarcia** [comment]
The link is still broken in the page I mentioned, though :o(

**Comment by RubenGarcia** [comment]
http://www.equalizergraphics.com/documents/Developer/API/internal/index.html
has a broken link to
Full API documentation for the public Equalizer API
http://www.equalizergraphics.com/documents/Developer/API-1.4/index.html
which also gives a 404.

**Comment by eile** [comment]
> The link is still broken in the page I mentioned, though :o(

Which is why this bug is still open. One step at a time.

**Comment by RubenGarcia** [comment]
Ah, sorry about that. Thanks for your work!

**Comment by RubenGarcia** [comment]
As of 27-10-2015, the link seems to have been updated on the webpage and points to the sequel documentation. Marking this closed now.
