### ISSUE TITLE
Compile error equalizer visual studio 2010

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#413]
When compiling Lunchbox, I get error C2242 in line 117 of pluginRegisterer.h

I changed the line to
		//rgh: changed class for typename here to avoid error C2242
        PluginFactory< typename Impl::PluginT >::getInstance().register_( plugin );

to make the error disappear, as advised by 
http://stackoverflow.com/questions/3406686/errors-porting-c-templates-from-gcc-to-visual-c

The same problem exists in lines 113, 95, 98, 99

**Comment by eile** [comment]
Just run across the same on clang. Will be fixed by Eyescale/Lunchbox#179

**Comment by RubenGarcia** [comment]
Great, thanks. There seem to be lots of problems with the windows build, I will try to document them as I come across them.

**Comment by eile** [comment]
If possible, please fix them and submit pull requests. The reason for the Windows errors is that few people are developing on it, so there is always bitrot setting in.
