### ISSUE TITLE
Compilation error on vs2010 compiling "pression"

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#414]
..\..\..\src\Pression\pression\pluginRegistry.cpp(33): fatal error C1083: Cannot open include file: 'os.h': No such file or directory

There is no "os.h" in the root, I think the correct include is "lunchbox/os.h"

However, changing that line gives me the following error:
5>..\..\..\src\Pression\pression\pluginRegistry.cpp(63): error C2039: 'getDirname' : is not a member of 'pression' [D:\Equalizer\Buildyard\build\Pression\pression\Pression.vcxproj]
5>..\..\..\src\Pression\pression\pluginRegistry.cpp(63): error C3861: 'getDirname': identifier not found [D:\Equalizer\Buildyard\build\Pression\pression\Pression.vcxproj]

I think this is a result of a broken macro for windows, GetModuleFileName. Please check and fix.

**Comment by RubenGarcia** [comment]
I stand corrected. These are the offending lines
#ifdef _WIN32
            if( GetModuleFileName( 0, cwd, MAXPATHLEN ) > 0 )
                directories.push_back( pression::getDirname( cwd ));
#else
and there does not seem to be any definition of pression::getDirname anywhere.
What is this function supposed to do?

**Comment by RubenGarcia** [comment]
Pull request added

**Comment by tribal-tec** [comment]
Fixed with https://github.com/Eyescale/Pression/pull/2
