### ISSUE TITLE
shader.cpp file can not find glewGetContext

### ISSUE THREAD

**Issue by lxq** [Eyescale/Equalizer#439]
The file eq/util/shader.cpp is not define glewGetContext, not like the other files such as eq/client/compositor.cpp. 
shader.h also does not define glewGetContext, so, in shader.cpp file I need how to do that?
thanks!

**Comment by lxq** [comment]
Can anyone give me an idea?

**Comment by eile** [comment]
Indeed shader needs a glewContext on windows. It should be passed to the functions and then defined similar to compositor.cpp:1600

@tribal-tec FYI

**Comment by lxq** [comment]
thanks a lot!
