### ISSUE TITLE
Is an issue about Deflect with Qt5?

### ISSUE THREAD

**Issue by lxq** [Eyescale/Equalizer#443]
I got the last Equalizer and Deflect from git source, which all support Qt5. When I use cmake with Equalizer under win 8.1 + vs2013,  it changed the line 48 from 'qt5_wrap_cpp' to 'qt4_wrap_cpp' in the  Deflect/deflect/CMakeLists.txt file. And then, the cmake shows it finds not suitable Qt version.
Does the last Equalizer work with the last Deflect well? Or, is there something that I do not know how to do?

**Comment by tribal-tec** [comment]
Possibly the SHA-1 of Deflect in .gitsubprojects is not pointing to the (latest) version that has the Qt5 support. Can you try that if that fixes it?

**Comment by lxq** [comment]
sure, I will try to do that.

**Comment by lxq** [comment]
I get the latest souce with changing .gitsubprojects file. It can build correctly with vs2013. But when I run eqHello demo,  it shows all GLEW_VERSION_X_X are GL_FALSE. In glWindow.cpp file , 'glewInit()' runs correctly.  I'm confused.

**Comment by tribal-tec** [comment]
I cannot reproduce that. You still observe that behavior? In the end, it's not a problem of Deflect, so I'd like to close this ticket if that's fine with you.

**Comment by lxq** [comment]
OK. You are right.
