### ISSUE TITLE
the bug in file eq/server/node.cpp

### ISSUE THREAD

**Issue by lxq** [Eyescale/Equalizer#446]
in file eq/server/node.cpp, line 449, the code is:
#endif // WIN32
    const boost::filesystem::path absolute =
        boost::filesystem::system_complete( boost::filesystem::path( program ));
    program = absolute.native();

The calling 'absolute.native();' value will be 'boost::filesystem::path::string_type'(std::wstring), but 'program' is 'std::string'. Because in boost/filesystem/path.hpp, it defines like:
# ifdef BOOST_WINDOWS_API
    typedef wchar_t                        value_type;
    typedef std::basic_string<value_type>  string_type;

**Comment by eile** [comment]
Can you submit a pull request with a fix? I don't have access to a Windows machine to reproduce and fix.

**Comment by lxq** [comment]
Sure. I will do it soon.

**Comment by tribal-tec** [comment]
see https://github.com/Eyescale/Equalizer/pull/449

**Comment by tribal-tec** [comment]
Fixed with https://github.com/Eyescale/Equalizer/pull/449
