### ISSUE TITLE
Build MVS2013

### ISSUE THREAD

**Issue by rarum** [Eyescale/Equalizer#456]
Hi all,

I built equalizer [Equalizer-master] on MVS 2013. I got warning

 Creating library R:/EQ/Equalizer-master/lib/Release/Equalizer.lib and object R:/EQ/Equalizer-master/lib/Release/Equalizer.exp
2>pipe.cpp.obj : warning LNK4217: locally defined symbol ?run@?$WorkerThread@VCommandQueue@eq@@@co@@MEAAXXZ (protected: virtual void __cdecl co::WorkerThread<class eq::CommandQueue>::run(void)) imported in function "protected: virtual void __cdecl eq::detail::RenderThread::run(void)" (?run@RenderThread@detail@eq@@MEAAXXZ)
2>  Equalizer.vcxproj -> R:\EQ\Equalizer-master\bin\Release\Equalizer.dll

When I run any example console window start but it is empty, no text no messages. No graphics Window is shown. I think problem could be in linker warning.

Ferry

**Comment by tribal-tec** [comment]
The warning was always there can/should be safely ignored for this matter.

I noticed that the startup deadlock is related to the lock in https://github.com/HBPVIS/Servus/blob/master/servus/uint128_t.cpp#L94, but I haven't fully understood why this happens, as this works fine on Linux.

Can you confirm by commenting this lock if it works for you then?

**Comment by tribal-tec** [comment]
This should fix it: https://github.com/Eyescale/hwsd/pull/37

**Comment by rarum** [comment]
I tried both fixes .... It works fine.

Many thanks
