### ISSUE TITLE
Qt-based windows hog the CPU

### ISSUE THREAD

**Issue by hernando** [Eyescale/Equalizer#467]
This can be observed by simply running eqPly -w Qt and stop the animation 

The problem is the message pump. A preliminary analysis points to a mismatch between the semantics of QEventLoop and eq::MessagePump which make it very difficult to implement dispatchOne being blocking. Maybe works as expected, but the application is looping around that function as fast as it can.

**Comment by eile** [comment]
Could not reproduce on OS X. Did you see this before or after I moved Window creation back to the main thread?

**Comment by hernando** [comment]
It was there after I changed the implementation. I cannot tell whether it  was there before.
