### ISSUE TITLE
Current master fails to compile under Xubuntu 14.04

### ISSUE THREAD

**Issue by PetrosKataras** [Eyescale/Equalizer#471]
Hi,

I just tried out to compile current master and it fails during configuration with :

```
CMake Error at Collage/tools/CMakeLists.txt:5 (include):
  include could not find load file:

    PurpleInstallPDB
```

I also see a couple of new names around like Servus, Purple ... I was wondering what is the roadmap these days for EQ.

**Comment by PetrosKataras** [comment]
[.gitsubprojects](https://github.com/Eyescale/Equalizer/blob/master/.gitsubprojects) is outdated. Collage should point to current master which is [60acf6d](https://github.com/Eyescale/Collage/commit/60acf6dda1c1feca27bf812b6d2e3958839f56dc) and not [137cfe8](https://github.com/Eyescale/Collage/commit/137cfe841f29ea112af53f47dc94fe549349d425) .

**Comment by eile** [comment]
Will update sub projects. This is an area of worry for us right now, please be patient until we have a way to make this more smooth.
