### ISSUE TITLE
Core profile support not picking correct gl version OS X Yosemite 10.10.4 with GLX

### ISSUE THREAD

**Issue by PetrosKataras** [Eyescale/Equalizer#492]
Hi, 

I would like to use the core profile support that was introduced with 2a6e92f651d . As far as I understand to enable it the only requirement is to define the relevant hints on the config file  

```
    EQ_WINDOW_IATTR_HINT_CORE_PROFILE ON  
    EQ_WINDOW_IATTR_HINT_OPENGL_MAJOR 3  
    EQ_WINDOW_IATTR_HINT_OPENGL_MINOR 2  
```
 which I did but the init of glWindow gives me 2.1 although I should have support for up to 4.1 :

```
41902.Draw0    lizer/eq/glx/windowSystem.cpp:70        3 Using glx::Pipe  
41902.Draw0    lizer/eq/glx/windowSystem.cpp:46      835 Using glx::Window  
41902.Draw0    ibs/equalizer/eq/glWindow.cpp:364     879 Window drawable config: GL2.1|GLEW2.1|rgb8a8|st8|DB
```

Am I missing something ? Sorry for posting it here in case this is not an issue and I m doing something wrong...

EDIT: Can confirm that the same is working properly under Linux ( xubuntu 14.04 ).

**Comment by tribal-tec** [comment]
AFAIK, using X11/GLX on Mac only gives you a legacy context up until Open 2.1. To go beyond, you are forced to use a core context, using Cocoa for instance. This is in theory possible using Qt as a window system for Equalizer (CMake option EQUALIZER_PREFER_QT), but according to @eile this only works for 32-bit.
While you are using 32-bit, the AGL window system is also available, but I don't know if this support core contexts at all, as AGL got deprecated by Apple a while ago.

I will try to make 64-bit Qt w/ Equalizer work first, as I don't have a 32-bit setup anymore.

**Comment by PetrosKataras** [comment]
Thanks for info! I realized my expectations where too high for GLX under OS X. In any case it would be great to try the Qt version once you have something since I am also right now on 64bit.
