### ISSUE TITLE
Deflect does not find libjpegturbo and cmake fails

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#497]
Current Equalizer as of today.

Ubuntu 14.04.3, tried both standard cmake (2.8.13) and latest (3.2.2). Both fail with the same error.
The packages libjpeg-turbo8-dev and libjpeg-turbo8 are installed, version 1.3.0-0ubuntu2

CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:344 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:506 (_pkg_check_modules_internal)
  CMake/common/CommonPackage.cmake:95 (pkg_check_modules)
  Deflect/CMakeLists.txt:26 (common_package)

-- Configuring incomplete, errors occurred!

**Comment by tribal-tec** [comment]
You also need to install libturbojpeg.

**Comment by RubenGarcia** [comment]
That worked, thanks!
A message somewhere in the CMakeLists.txt might be useful for other users.
