### ISSUE TITLE
Incorrect information in downloads/source.html

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#512]
http://www.equalizergraphics.com/downloads/source.html
says
..."The easiest way is to build using Buildyard,"...
but buildyard is no longer used.
Please update the webpage.

**Comment by wangzilu** [comment]
Have you built equalizer successfully?

**Comment by RubenGarcia** [comment]
The git version from 12 days ago compiled successfully, yes.
cmake ..; make 
worked.

**Comment by eile** [comment]
Thanks, fixed in git. We're transitioning the old web server over to github pages, so it will be fixed online later.
