### ISSUE TITLE
Current git (Fri Nov 13 12:23:15 CET 2015) cmake error on ubuntu 14.04

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#513]
mkdir build; cd build; cmake ..
gives the following output:

-- Configured vmmlib [2bec113] with Boost
-- Configured Servus [26b1ad0] with avahi-client Boost Threads
-- Configured Lunchbox [33546f1] with Boost hwloc leveldb MPI OpenMP Servus WITHOUT skv
-- Configured Pression [93883cf] with Boost LibJpegTurbo Lunchbox OpenMP
-- Configured hwsd [0ecf64a] with Boost Lunchbox OpenGL Qt5Core Qt5Network Servus X11
-- Configured Collage [182698e] with Boost Lunchbox OFED Pression UDT
-- Configured GLStats [3c76246] with Lunchbox OpenGL
-- Configured Deflect [8556bc3] with Boost GLUT LibJpegTurbo OpenGL Qt5Concurrent Qt5Core Qt5Network Qt5Widgets Servus
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file):
  configure_file called with unknown argument(s):

   COPY_ONLY

Call Stack (most recent call first):
  CMake/common/CommonQtSupport.cmake:41 (qt5_add_resources)
  CMake/common/CommonApplication.cmake:45 (common_qt_support)
  CMake/common/CommonApplication.cmake:122 (_common_application)
  CMake/common/CommonApplication.cmake:66 (_common_gui_application)
  Deflect/apps/DesktopStreamer/CMakeLists.txt:49 (common_gui_application)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configured Equalizer [ce90e9d] with Boost Collage Deflect GLStats hwsd Lunchbox MAGELLAN OpenCV OpenGL OpenSceneGraph Pression Qt5Core Qt5Gui Qt5Widgets vmmlib VRPN X11 GLEW_MX WITHOUT hwloc
CMake Error at CMake/common/CommonCPack.cmake:12 (message):
  Missing CPACK_PACKAGE_LICENSE
Call Stack (most recent call first):
  CMake/CPackConfig.cmake:24 (include)
  CMakeLists.txt:102 (include)

-- Configuring incomplete, errors occurred!

There is no mention of COPY_ONLY or CPACK_PACKAGE_LICENSE in the readme file.

**Comment by RubenGarcia** [comment]
Explicitly setting the license works, for example 
cmake -DCPACK_PACKAGE_LICENSE="BSD" ..
Please add this to the readme or add the correct license in the correct CMaleLists.txt

**Comment by eile** [comment]
Your CMake/common is out of date. Remove the directory and let cmake re-clone it.

**Comment by RubenGarcia** [comment]
Recloned, now cmake works. Thanks. Closing.

**Comment by RubenGarcia** [comment]
Just out of curiosity, shouldn't
git pull
have updated CMake/common?

And if not, could we add a comment on the Readme file? Something along the lines that git pull is not enough to update?

**Comment by eile** [comment]
> shouldn't git pull have updated CMake/common?

No, git does not update any of the externals/sub projects. There is an explicit 'rebase' target doing this, but if your CMake run fails you're deadlocked. git clean -ffdx should do the trick, instead of recloning everything.
