### ISSUE TITLE
GLEW conflicts with GL of OSG

### ISSUE THREAD

**Issue by lxq** [Eyescale/Equalizer#519]
My eq cmakes with GLEW and OSG. When compiling , the image.cpp file of Equalizer project will conflict with GL of OSG. The information is that image.cpp file used:
    #ifdef EQUALIZER_USE_OPENSCENEGRAPH
    #  include <osgDB/WriteFile>
    #endif
So, OSG has its own GL extensions. But equalizer is coming with glew. so it Conflicts.
Can anyone help me ?

**Comment by eile** [comment]
https://github.com/Eyescale/Equalizer/blob/master/doc/FAQ#L2

**Comment by lxq** [comment]
Thank you very much,Eile.
