### ISSUE TITLE
Equalizer & updating opengl.org "sdk" area

### ISSUE THREAD

**Issue by oddhack** [Eyescale/Equalizer#614]
We're going to be restructuring the SDK area of www.opengl.org and, since Equalizer is listed there, wanted to ask what the current state of the project is, and if it should continue to be listed as a current resource.

Jon Leech
Khronos

**Comment by eile** [comment]
Hi Jon,

> We're going to be restructuring the SDK area of www.opengl.org and, since Equalizer is listed there, wanted to ask what the current state of the project is, and if it should continue to be listed as a current resource.

Equalizer is still active, although development has slowed since it reached feature completeness. I would be happy to have it listed as a resource in the future.


Best,

Stefan.
