### ISSUE TITLE
NoThing working after make install (Ubuntu)

### ISSUE THREAD

**Issue by ErwannH** [Eyescale/Equalizer#618]
Hello;

Using Equalizer with Livre project

Built using Livre Cmake.

Building: OK
Running demo from build location: OK
Install in custom location, run the demo: KO 

9 Initializing compression DSO /data_local/j0334308/Livre_build/lib/libPression.so.2.0.0 failed, 0 compression engines reported
Erreur de segmentation (core dumped)

Demo KO when target thee INSTALL/lib location
Demo OK when target thee BUILD_LOCATION/lib location

My feeling is some environnement variable are recorded in the lib for plugin loading.

Any idea to help me?

**Comment by ErwannH** [comment]
Is that OK now?  Can I test it again?

**Comment by eile** [comment]
There is still an issue with static initialization. I'll close the bug once it works and is merged.

**Comment by eile** [comment]
For now, run from the build tree. Not sure if I'll succeed today.

**Comment by eile** [comment]
Fixed by #619
