### ISSUE TITLE
eqPly crash with QT

### ISSUE THREAD

**Issue by ErwannH** [Eyescale/Equalizer#621]
Hello;

Tying now to integrate Livre in a Simple QT Widget. I started by testing Equalizer eqPly demo over QT....

getting the following crash

QObject::connect: Cannot connect (null)::destroyImpl( detail::Window* ) to eq::qt::WindowFactory::onDestroyImpl( detail::Window* )
 3664.Draw0    aster/Equalizer/eq/window.cpp:416      11 Assert: systemWindow  in: 
  12: lunchbox::abort(bool)
  11: eq::Window::configInitSystemWindow(servus::uint128_t const&)
  10: eqPly::Window::configInitSystemWindow(servus::uint128_t const&)
  9: eq::Window::configInit(servus::uint128_t const&)
  8: eq::Window::_cmdConfigInit(co::ICommand&)
  7: co::CommandFunc<co::Dispatcher>::operator()(co::ICommand&)
  6: co::ICommand::operator()()
  5: co::WorkerThread<eq::CommandQueue>::run()
  4: eq::detail::RenderThread::run()
  3: lunchbox::Thread::_runChild()
  2: lunchbox::Thread::runChild(void*)
  1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fa5b40f56ba]
  0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fa5b311282d]

Abandon (core dumped)

By the way some advice about Equalizer integration in a standalone QT App could be helpfull (simple demo?). I found eqqt project on sourceforce. Seems to be partly integrated in eq/qt part.

Could you help me?

Regards (and thanks for the last fix it's ok now)

**Comment by eile** [comment]
Regression in 6cef1f4354f208757b6a5012e0accee94f086c2b
