### ISSUE TITLE
any gui can intergrate with equalizer?

### ISSUE THREAD

**Issue by caishanli** [Eyescale/Equalizer#635]
Is there any or gui lib can intergrate with equalizer? I want to have some gui like buttons and labels in my equalizer based application with multi nodes and multi windows.Thank you!

**Comment by eile** [comment]
You can use Qt with the Qt integration provided by Equalizer.

**Comment by caishanli** [comment]
I want to render osgearth with equalizer with one machine multi windows and multi machines multi screens, and have some gui to control the earth and do some measurment. But I don't know is it possbile, and problems to be faced. Could you give me some suggestions about what I need to pay attention to. Thank you!

**Comment by caishanli** [comment]
Any examples of Qt integration provided by Equalizer?

**Comment by eile** [comment]
```eqPly -w Qt``` creates a QGLWidget, although it does not have an UI

**Comment by jaeguyoon** [comment]
Does the equalizer using Qt window system support to render with 2D scalability mode on two Ubuntu machines?  
In the eqPly example, there is a comment like "no working multi GPU setup for Qt yet.."

**Comment by eile** [comment]
Multi-GPU refers to multiple GPUs in a single machine in multi-threaded rendering mode. 2D across two machines should work.
