### ISSUE TITLE
is there any demo about how to use qt creat window

### ISSUE THREAD

**Issue by wpw17** [Eyescale/Equalizer#658]
hello,i want to use qt to creat a window which contain Button,Text......what should i do,i add that in eqPly/main.cpp,but it doesnot run,is there anything wrong,what shou i do?
```
QPushButton* b = new QPushButton();
QWidget* g = QWidget::createWindowContainer(qtWindow);
QWidget* h = new QWidget();
g->setParent(h);
```

**Comment by eile** [comment]
Equalizer windows can be Qt windows, but you have to select Qt as a window system. eqPly can do this. You then want to set up your Qt stuff from the corresponding eq::Window.
